version: 2
models:
- name: snowplow_sessions
  columns:
  - name: session_id
    tests:
    - not_null
    - relationships:
        field: session_id
        to: ref('snowplow_page_views')
    - unique
